Update token list in configure-registry

diff --git a/scripts/configure-registry b/scripts/configure-registry
--- a/scripts/configure-registry
+++ b/scripts/configure-registry
@@ -1,9 +1,7 @@
 #!/bin/bash -eu
 
 PROTOCOLS="0x02ad05d3 0x395ca9f1 0x85ccc7d5 0x9498325a"
-TOKENLIST="$(dirname "$0")/../dist/tokenlist.json"
-NTN_SYMBOL='NTN'
-USDC_SYMBOL='tUSDC.pol'
+TOKENLIST="$(dirname "$0")/../tokenlists/tokenlist-65100003.json"
 
 for cmd in airswap expect jq; do
     if ! type "${cmd}" &>/dev/null; then
@@ -13,7 +11,7 @@ for cmd in airswap expect jq; do
 done
 
 if ! [[ -f "${TOKENLIST}" ]]; then
-    echo "Missing dist/tokenlist.json; generate token list first" >&2
+    echo "File not found: ${TOKENLIST}" >&2
     exit 1
 fi
 
@@ -79,7 +77,7 @@ TOKENS="$(echo -n "$(jq -r '.tokens[].symbol' "${TOKENLIST}")" | tr ' ' ',')"
 expect <<-DONE
 	spawn airswap tokens:add
 	expect "token symbols to activate"
-	send -- "${NTN_SYMBOL},${USDC_SYMBOL},${TOKENS}"
+	send -- "${TOKENS}"
 	expect "Type*to send"
 	send -- "yes\r"
 	expect EOF
